Background and hover effect added
metakgp/travel-buddy pull request #20
Opened 2024-12-10 19:46 UTC by Archi-shaw

![Screenshot 2024-12-11 011922](https://github.com/user-attachments/assets/953dd7f6-2935-4443-a032-dfdefd7a2849)

2024-12-11 22:22 UTC, Archi-shaw commented
@saharsh-agrawal  Please review the PR.

2024-12-12 10:51 UTC, saharsh-agrawal reviewed
1) Your bg code is messing up the outer and inner container and vertical align of the pages. Please review that.
2) I guess we are doing overdoin the button design and animation a lot, especially with those big shadows. A simple, sleek and subtle design woould be perfect. Also, you may need to chnage the contrast of the colours of the background and foreground elements.
3) Do not use "Track My Trips" and "Train Trails" outside as it causes unnecessary confusion. Tracking your existing trips is already a different page and button on each of these two pages.

2024-12-13 19:00 UTC, saharsh-agrawal requested changes
They are fine for now, just let the background be blank for now, because of we put anything, it needs to be done for all pages (not just 3) and suit all of them well. 
Also, put your changes for Contri button and Generic labels in this PR itself and let us go for it.

2024-12-13 19:39 UTC, saharsh-agrawal approved these changes

2024-12-13 19:39 UTC, saharsh-agrawal approved these changes

2024-12-13 19:40 UTC, merged